"""Add TCUStatistic model for structured TCU statistics

Revision ID: c05a1e02576b
Revises: f91920642ccd
Create Date: 2026-09-18 09:29:49.200380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c05a1e02576b'
down_revision: Union[str, None] = 'f91920642ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tcu_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('statistic_type', sa.Enum('UNIVERSITY_INSTITUTIONS', 'ACADEMIC_PROGRAMMES', 'ACCREDITED_UNIVERSITIES', 'REGISTERED_STUDENTS', 'GRADUATES', 'STAFF_COUNT', 'CAMPUSES', 'FACULTIES', 'DEPARTMENTS', 'OTHER', name='tcustatistictype'), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_page_title', sa.String(length=255), nullable=True),
    sa.Column('source_section', sa.String(length=255), nullable=True),
    sa.Column('academic_year_id', sa.String(length=36), nullable=True),
    sa.Column('academic_year_label', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_name', 'academic_year_label', name='uq_tcu_statistic_metric_year')
    )
    op.create_index(op.f('ix_tcu_statistics_is_verified'), 'tcu_statistics', ['is_verified'], unique=False)
    op.create_index(op.f('ix_tcu_statistics_metric_name'), 'tcu_statistics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_tcu_statistics_statistic_type'), 'tcu_statistics', ['statistic_type'], unique=False)
    op.alter_column('admission_requirements', 'qualification_type',
               existing_type=postgresql.ENUM('A_LEVEL', 'DIPLOMA', 'CERTIFICATE', 'MATURE', 'FOREIGN', 'EQUIVALENT', name='qualificationtype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admission_requirements', 'qualification_type',
               existing_type=postgresql.ENUM('A_LEVEL', 'DIPLOMA', 'CERTIFICATE', 'MATURE', 'FOREIGN', 'EQUIVALENT', name='qualificationtype'),
               nullable=True)
    op.drop_index(op.f('ix_tcu_statistics_statistic_type'), table_name='tcu_statistics')
    op.drop_index(op.f('ix_tcu_statistics_metric_name'), table_name='tcu_statistics')
    op.drop_index(op.f('ix_tcu_statistics_is_verified'), table_name='tcu_statistics')
    op.drop_table('tcu_statistics')
    # ### end Alembic commands ###
