"""Add verification fields, AcademicYear, FeeStructure, SubjectRequirement, IngestionJob, aliases

Revision ID: f91920642ccd
Revises: a833069c8d46
Create Date: 2026-09-17 22:05:43.576289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Enum types for use in both upgrade and downgrade
qualificationtype_enum = sa.Enum('A_LEVEL', 'DIPLOMA', 'CERTIFICATE', 'MATURE', 'FOREIGN', 'EQUIVALENT', name='qualificationtype')
programmelevel_enum = sa.Enum('CERTIFICATE', 'DIPLOMA', 'BACHELOR', 'MASTER', 'PHD', name='programmelevel')
studymode_enum = sa.Enum('FULL_TIME', 'PART_TIME', 'DISTANCE', 'ONLINE', name='studymode')
programmestatus_enum = sa.Enum('VERIFIED', 'UNVERIFIED', 'INACTIVE', 'UNKNOWN', name='programmestatus')
universitystatus_enum = sa.Enum('VERIFIED', 'UNVERIFIED', 'INACTIVE', 'UNKNOWN', name='universitystatus')
sourcetype_enum = sa.Enum('TCU_OFFICIAL', 'UNIVERSITY_OFFICIAL', 'HESLB', 'NACTVET', 'GOVERNMENT', 'OTHER', name='sourcetype')
sourceauthority_enum = sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', name='sourceauthority')


# revision identifiers, used by Alembic.
revision: str = 'f91920642ccd'
down_revision: Union[str, None] = 'a833069c8d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    qualificationtype_enum.create(op.get_bind(), checkfirst=True)
    programmelevel_enum.create(op.get_bind(), checkfirst=True)
    studymode_enum.create(op.get_bind(), checkfirst=True)
    programmestatus_enum.create(op.get_bind(), checkfirst=True)
    universitystatus_enum.create(op.get_bind(), checkfirst=True)
    sourcetype_enum.create(op.get_bind(), checkfirst=True)
    sourceauthority_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('academic_years',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('year_label', sa.String(length=20), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_year', 'end_year', name='uq_academic_year_range'),
    sa.UniqueConstraint('year_label')
    )
    op.create_index(op.f('ix_academic_years_is_current'), 'academic_years', ['is_current'], unique=False)
    op.create_table('university_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('university_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_aliases_alias'), 'university_aliases', ['alias'], unique=False)
    op.create_table('fee_structures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('programme_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year_id', sa.String(length=36), nullable=False),
    sa.Column('tuition_fee_tzs', sa.Integer(), nullable=True),
    sa.Column('fee_currency', sa.String(length=3), nullable=True),
    sa.Column('registration_fee_tzs', sa.Integer(), nullable=True),
    sa.Column('examination_fee_tzs', sa.Integer(), nullable=True),
    sa.Column('library_fee_tzs', sa.Integer(), nullable=True),
    sa.Column('medical_fee_tzs', sa.Integer(), nullable=True),
    sa.Column('student_union_fee_tzs', sa.Integer(), nullable=True),
    sa.Column('other_fees_tzs', sa.Integer(), nullable=True),
    sa.Column('other_fees_description', sa.Text(), nullable=True),
    sa.Column('total_estimated_tzs', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('target_university_id', sa.String(length=36), nullable=True),
    sa.Column('target_programme_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('documents_found', sa.Integer(), nullable=True),
    sa.Column('documents_new', sa.Integer(), nullable=True),
    sa.Column('documents_updated', sa.Integer(), nullable=True),
    sa.Column('documents_failed', sa.Integer(), nullable=True),
    sa.Column('last_content_hash', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_programme_id'], ['programmes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programme_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('programme_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programme_aliases_alias'), 'programme_aliases', ['alias'], unique=False)
    op.create_table('subject_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('programme_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year_id', sa.String(length=36), nullable=True),
    sa.Column('qualification_type', sa.String(length=100), nullable=False),
    sa.Column('required_subjects', sa.Text(), nullable=False),
    sa.Column('subject_combination', sa.String(length=50), nullable=True),
    sa.Column('minimum_grades', sa.String(length=100), nullable=True),
    sa.Column('minimum_points', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('alternative_qualifications', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admission_requirements', sa.Column('academic_year_id', sa.String(length=36), nullable=True))
    op.add_column('admission_requirements', sa.Column('required_subjects', sa.Text(), nullable=True))
    op.add_column('admission_requirements', sa.Column('subject_combination', sa.String(length=50), nullable=True))
    op.add_column('admission_requirements', sa.Column('minimum_grades', sa.String(length=100), nullable=True))
    op.add_column('admission_requirements', sa.Column('minimum_points', sa.Integer(), nullable=True))
    op.add_column('admission_requirements', sa.Column('alternative_requirements', sa.Text(), nullable=True))
    op.add_column('admission_requirements', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('admission_requirements', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('admission_requirements', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('admission_requirements', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('admission_requirements', 'qualification_type',
               existing_type=sa.VARCHAR(length=100),
               type_=qualificationtype_enum,
               postgresql_using="qualification_type::qualificationtype",
               nullable=True)
    op.create_foreign_key(None, 'admission_requirements', 'academic_years', ['academic_year_id'], ['id'])
    op.drop_column('admission_requirements', 'subjects')
    op.drop_column('admission_requirements', 'grades')
    op.drop_column('admission_requirements', 'points')
    op.drop_column('admission_requirements', 'academic_year')
    op.add_column('documents', sa.Column('academic_year_id', sa.String(length=36), nullable=True))
    op.add_column('documents', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('embedding_model_version', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'documents', 'academic_years', ['academic_year_id'], ['id'])
    op.add_column('programmes', sa.Column('tcu_accredited', sa.Boolean(), nullable=True))
    op.add_column('programmes', sa.Column('tcu_programme_code', sa.String(length=100), nullable=True))
    op.add_column('programmes', sa.Column('tcu_accreditation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('programmes', sa.Column('tcu_status', programmestatus_enum, nullable=True))
    op.add_column('programmes', sa.Column('tcu_last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('programmes', sa.Column('tcu_source_url', sa.String(length=500), nullable=True))
    op.add_column('programmes', sa.Column('tuition_fee_tzs', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('programmes', sa.Column('fee_currency', sa.String(length=3), nullable=True))
    op.add_column('programmes', sa.Column('fee_year', sa.String(length=20), nullable=True))
    op.add_column('programmes', sa.Column('fee_source_url', sa.String(length=500), nullable=True))
    op.add_column('programmes', sa.Column('fee_last_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('programmes', sa.Column('heslb_eligible', sa.Boolean(), nullable=True))
    op.add_column('programmes', sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('programmes', sa.Column('intake_months', sa.String(length=100), nullable=True))
    op.add_column('programmes', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('programmes', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('programmes', 'level',
               existing_type=sa.VARCHAR(length=50),
               type_=programmelevel_enum,
               postgresql_using="level::programmelevel",
               nullable=False)
    op.alter_column('programmes', 'study_mode',
               existing_type=sa.VARCHAR(length=50),
               type_=studymode_enum,
               postgresql_using="study_mode::studymode",
               existing_nullable=True)
    op.add_column('scholarships', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('scholarships', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('scholarships', sa.Column('amount_tzs', sa.Integer(), nullable=True))
    op.add_column('scholarships', sa.Column('academic_year_id', sa.String(length=36), nullable=True))
    op.add_column('scholarships', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('scholarships', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'scholarships', 'academic_years', ['academic_year_id'], ['id'])
    op.add_column('sources', sa.Column('authority_level', sourceauthority_enum, nullable=True))
    op.add_column('sources', sa.Column('academic_year_id', sa.String(length=36), nullable=True))
    op.add_column('sources', sa.Column('section_title', sa.String(length=255), nullable=True))
    op.add_column('sources', sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.alter_column('sources', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sourcetype_enum,
               postgresql_using="source_type::sourcetype",
               nullable=False)
    op.create_foreign_key(None, 'sources', 'academic_years', ['academic_year_id'], ['id'])
    op.add_column('universities', sa.Column('tcu_accredited', sa.Boolean(), nullable=True))
    op.add_column('universities', sa.Column('tcu_registration_number', sa.String(length=100), nullable=True))
    op.add_column('universities', sa.Column('tcu_accreditation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('universities', sa.Column('tcu_status', universitystatus_enum, nullable=True))
    op.add_column('universities', sa.Column('tcu_last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('universities', sa.Column('tcu_source_url', sa.String(length=500), nullable=True))
    op.add_column('universities', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('universities', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'universities', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'universities', type_='unique')
    op.drop_column('universities', 'last_verified_at')
    op.drop_column('universities', 'source_url')
    op.drop_column('universities', 'tcu_source_url')
    op.drop_column('universities', 'tcu_last_verified_at')
    op.drop_column('universities', 'tcu_status')
    op.drop_column('universities', 'tcu_accreditation_date')
    op.drop_column('universities', 'tcu_registration_number')
    op.drop_column('universities', 'tcu_accredited')
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.alter_column('sources', 'source_type',
               existing_type=sourcetype_enum,
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('sources', 'content_hash')
    op.drop_column('sources', 'last_crawled_at')
    op.drop_column('sources', 'section_title')
    op.drop_column('sources', 'academic_year_id')
    op.drop_column('sources', 'authority_level')
    op.drop_constraint(None, 'scholarships', type_='foreignkey')
    op.drop_column('scholarships', 'verified_at')
    op.drop_column('scholarships', 'is_verified')
    op.drop_column('scholarships', 'academic_year_id')
    op.drop_column('scholarships', 'amount_tzs')
    op.drop_column('scholarships', 'source_type')
    op.drop_column('scholarships', 'source_url')
    op.alter_column('programmes', 'study_mode',
               existing_type=studymode_enum,
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('programmes', 'level',
               existing_type=programmelevel_enum,
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('programmes', 'last_verified_at')
    op.drop_column('programmes', 'source_url')
    op.drop_column('programmes', 'intake_months')
    op.drop_column('programmes', 'application_deadline')
    op.drop_column('programmes', 'heslb_eligible')
    op.drop_column('programmes', 'fee_last_updated')
    op.drop_column('programmes', 'fee_source_url')
    op.drop_column('programmes', 'fee_year')
    op.drop_column('programmes', 'fee_currency')
    op.drop_column('programmes', 'tuition_fee_tzs')
    op.drop_column('programmes', 'tcu_source_url')
    op.drop_column('programmes', 'tcu_last_verified_at')
    op.drop_column('programmes', 'tcu_status')
    op.drop_column('programmes', 'tcu_accreditation_date')
    op.drop_column('programmes', 'tcu_programme_code')
    op.drop_column('programmes', 'tcu_accredited')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'embedding_model_version')
    op.drop_column('documents', 'source_type')
    op.drop_column('documents', 'academic_year_id')
    op.add_column('admission_requirements', sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('admission_requirements', sa.Column('points', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('admission_requirements', sa.Column('grades', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('admission_requirements', sa.Column('subjects', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admission_requirements', type_='foreignkey')
    op.alter_column('admission_requirements', 'qualification_type',
               existing_type=qualificationtype_enum,
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('admission_requirements', 'verified_at')
    op.drop_column('admission_requirements', 'is_verified')
    op.drop_column('admission_requirements', 'source_type')
    op.drop_column('admission_requirements', 'source_url')
    op.drop_column('admission_requirements', 'alternative_requirements')
    op.drop_column('admission_requirements', 'minimum_points')
    op.drop_column('admission_requirements', 'minimum_grades')
    op.drop_column('admission_requirements', 'subject_combination')
    op.drop_column('admission_requirements', 'required_subjects')
    op.drop_column('admission_requirements', 'academic_year_id')
    op.drop_table('subject_requirements')
    op.drop_index(op.f('ix_programme_aliases_alias'), table_name='programme_aliases')
    op.drop_table('programme_aliases')
    op.drop_table('ingestion_jobs')
    op.drop_table('fee_structures')
    op.drop_index(op.f('ix_university_aliases_alias'), table_name='university_aliases')
    op.drop_table('university_aliases')
    op.drop_index(op.f('ix_academic_years_is_current'), table_name='academic_years')
    op.drop_table('academic_years')
    # Drop enum types
    qualificationtype_enum.drop(op.get_bind(), checkfirst=True)
    programmelevel_enum.drop(op.get_bind(), checkfirst=True)
    studymode_enum.drop(op.get_bind(), checkfirst=True)
    programmestatus_enum.drop(op.get_bind(), checkfirst=True)
    universitystatus_enum.drop(op.get_bind(), checkfirst=True)
    sourcetype_enum.drop(op.get_bind(), checkfirst=True)
    sourceauthority_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
